//! GENERATED by tools/pd-assets/pd_ids.py from reference/pd-decomp (NTSC final). Do not edit:
//! change the generator and rerun it.
//!
//! PD's enumerations under PD's names, so a value can be looked up in the decomp
//! directly. Sound ids are keyed in `assets/sfx/manifest.json` and FILE_* numbers in
//! `assets/models/index.json`.
#![allow(dead_code)]

// `enum weaponnum` (`constants.h:4561`) and the `WEAPON_*` defines.
pub const WEAPON_NONE: u8 = 0;
pub const WEAPON_UNARMED: u8 = 1;
pub const WEAPON_FALCON2: u8 = 2;
pub const WEAPON_FALCON2_SILENCER: u8 = 3;
pub const WEAPON_FALCON2_SCOPE: u8 = 4;
pub const WEAPON_MAGSEC4: u8 = 5;
pub const WEAPON_MAULER: u8 = 6;
pub const WEAPON_PHOENIX: u8 = 7;
pub const WEAPON_DY357MAGNUM: u8 = 8;
pub const WEAPON_DY357LX: u8 = 9;
pub const WEAPON_CMP150: u8 = 10;
pub const WEAPON_CYCLONE: u8 = 11;
pub const WEAPON_CALLISTO: u8 = 12;
pub const WEAPON_RCP120: u8 = 13;
pub const WEAPON_LAPTOPGUN: u8 = 14;
pub const WEAPON_DRAGON: u8 = 15;
pub const WEAPON_K7AVENGER: u8 = 16;
pub const WEAPON_AR34: u8 = 17;
pub const WEAPON_SUPERDRAGON: u8 = 18;
pub const WEAPON_SHOTGUN: u8 = 19;
pub const WEAPON_REAPER: u8 = 20;
pub const WEAPON_SNIPERRIFLE: u8 = 21;
pub const WEAPON_FARSIGHT: u8 = 22;
pub const WEAPON_DEVASTATOR: u8 = 23;
pub const WEAPON_ROCKETLAUNCHER: u8 = 24;
pub const WEAPON_SLAYER: u8 = 25;
pub const WEAPON_COMBATKNIFE: u8 = 26;
pub const WEAPON_CROSSBOW: u8 = 27;
pub const WEAPON_TRANQUILIZER: u8 = 28;
pub const WEAPON_LASER: u8 = 29;
pub const WEAPON_GRENADE: u8 = 30;
pub const WEAPON_NBOMB: u8 = 31;
pub const WEAPON_TIMEDMINE: u8 = 32;
pub const WEAPON_PROXIMITYMINE: u8 = 33;
pub const WEAPON_REMOTEMINE: u8 = 34;
pub const WEAPON_COMBATBOOST: u8 = 35;
pub const WEAPON_PP9I: u8 = 36;
pub const WEAPON_CC13: u8 = 37;
pub const WEAPON_KL01313: u8 = 38;
pub const WEAPON_KF7SPECIAL: u8 = 39;
pub const WEAPON_ZZT: u8 = 40;
pub const WEAPON_DMC: u8 = 41;
pub const WEAPON_AR53: u8 = 42;
pub const WEAPON_RCP45: u8 = 43;
pub const WEAPON_PSYCHOSISGUN: u8 = 44;
pub const WEAPON_NIGHTVISION: u8 = 45;
pub const WEAPON_EYESPY: u8 = 46;
pub const WEAPON_XRAYSCANNER: u8 = 47;
pub const WEAPON_IRSCANNER: u8 = 48;
pub const WEAPON_CLOAKINGDEVICE: u8 = 49;
pub const WEAPON_HORIZONSCANNER: u8 = 50;
pub const WEAPON_TESTER: u8 = 51;
pub const WEAPON_KINGSCEPTRE: u8 = 52;
pub const WEAPON_ECMMINE: u8 = 53;
pub const WEAPON_DATAUPLINK: u8 = 54;
pub const WEAPON_RTRACKER: u8 = 55;
pub const WEAPON_PRESIDENTSCANNER: u8 = 56;
pub const WEAPON_DOORDECODER: u8 = 57;
pub const WEAPON_AUTOSURGEON: u8 = 58;
pub const WEAPON_EXPLOSIVES: u8 = 59;
pub const WEAPON_SKEDARBOMB: u8 = 60;
pub const WEAPON_COMMSRIDER: u8 = 61;
pub const WEAPON_TRACERBUG: u8 = 62;
pub const WEAPON_TARGETAMPLIFIER: u8 = 63;
pub const WEAPON_DISGUISE40: u8 = 64;
pub const WEAPON_DISGUISE41: u8 = 65;
pub const WEAPON_FLIGHTPLANS: u8 = 66;
pub const WEAPON_RESEARCHTAPE: u8 = 67;
pub const WEAPON_BACKUPDISK: u8 = 68;
pub const WEAPON_KEYCARD45: u8 = 69;
pub const WEAPON_KEYCARD46: u8 = 70;
pub const WEAPON_KEYCARD47: u8 = 71;
pub const WEAPON_KEYCARD48: u8 = 72;
pub const WEAPON_KEYCARD49: u8 = 73;
pub const WEAPON_KEYCARD4A: u8 = 74;
pub const WEAPON_KEYCARD4B: u8 = 75;
pub const WEAPON_KEYCARD4C: u8 = 76;
pub const WEAPON_SUITCASE: u8 = 77;
pub const WEAPON_BRIEFCASE: u8 = 78;
pub const WEAPON_SHIELDTECHITEM: u8 = 79;
pub const WEAPON_NECKLACE: u8 = 80;
pub const WEAPON_HAMMER: u8 = 81;
pub const WEAPON_SCREWDRIVER: u8 = 82;
pub const WEAPON_ROCKET: u8 = 83;
pub const WEAPON_HOMINGROCKET: u8 = 84;
pub const WEAPON_GRENADEROUND: u8 = 85;
pub const WEAPON_BOLT: u8 = 86;
pub const WEAPON_BRIEFCASE2: u8 = 87;
pub const WEAPON_SKROCKET: u8 = 88;
pub const WEAPON_CHOPPERGUN: u8 = 89;
pub const WEAPON_WATCHLASER: u8 = 90;
pub const WEAPON_MPSHIELD: u8 = 91;
pub const WEAPON_DISABLED: u8 = 92;
pub const WEAPON_SUICIDEPILL: u8 = 93;
pub const WEAPON_MPLOCATION00: u8 = 240;
pub const WEAPON_MPLOCATION01: u8 = 241;
pub const WEAPON_MPLOCATION02: u8 = 242;
pub const WEAPON_MPLOCATION03: u8 = 243;
pub const WEAPON_MPLOCATION04: u8 = 244;
pub const WEAPON_MPLOCATION05: u8 = 245;
pub const WEAPON_MPLOCATION06: u8 = 246;
pub const WEAPON_MPLOCATION07: u8 = 247;
pub const WEAPON_MPLOCATION08: u8 = 248;
pub const WEAPON_MPLOCATION09: u8 = 249;
pub const WEAPON_MPLOCATION10: u8 = 250;
pub const WEAPON_MPLOCATION11: u8 = 251;
pub const WEAPON_MPLOCATION12: u8 = 252;
pub const WEAPON_MPLOCATION13: u8 = 253;
pub const WEAPON_MPLOCATION14: u8 = 254;
pub const WEAPON_MPLOCATION15: u8 = 255;

// Stage numbers (`constants.h`).
pub const STAGE_MP_RANDOM: u8 = 0x1;
pub const STAGE_MAIANSOS: u8 = 0x9;
pub const STAGE_TEST_SILO: u8 = 0x14;
pub const STAGE_WAR: u8 = 0x16;
pub const STAGE_MP_RAVINE: u8 = 0x17;
pub const STAGE_TEST_ARCH: u8 = 0x18;
pub const STAGE_ESCAPE: u8 = 0x19;
pub const STAGE_TEST_DEST: u8 = 0x1a;
pub const STAGE_RETAKING: u8 = 0x1b;
pub const STAGE_CRASHSITE: u8 = 0x1c;
pub const STAGE_CHICAGO: u8 = 0x1d;
pub const STAGE_G5BUILDING: u8 = 0x1e;
pub const STAGE_MP_COMPLEX: u8 = 0x1f;
pub const STAGE_MP_G5BUILDING: u8 = 0x20;
pub const STAGE_PELAGIC: u8 = 0x21;
pub const STAGE_EXTRACTION: u8 = 0x22;
pub const STAGE_TEST_RUN: u8 = 0x23;
pub const STAGE_24: u8 = 0x24;
pub const STAGE_MP_TEMPLE: u8 = 0x25;
pub const STAGE_CITRAINING: u8 = 0x26;
pub const STAGE_AIRBASE: u8 = 0x27;
pub const STAGE_28: u8 = 0x28;
pub const STAGE_MP_PIPES: u8 = 0x29;
pub const STAGE_SKEDARRUINS: u8 = 0x2a;
pub const STAGE_2B: u8 = 0x2b;
pub const STAGE_VILLA: u8 = 0x2c;
pub const STAGE_DEFENSE: u8 = 0x2d;
pub const STAGE_TEST_ASH: u8 = 0x2e;
pub const STAGE_INFILTRATION: u8 = 0x2f;
pub const STAGE_DEFECTION: u8 = 0x30;
pub const STAGE_AIRFORCEONE: u8 = 0x31;
pub const STAGE_MP_SKEDAR: u8 = 0x32;
pub const STAGE_INVESTIGATION: u8 = 0x33;
pub const STAGE_ATTACKSHIP: u8 = 0x34;
pub const STAGE_RESCUE: u8 = 0x35;
pub const STAGE_TEST_LEN: u8 = 0x36;
pub const STAGE_MBR: u8 = 0x37;
pub const STAGE_DEEPSEA: u8 = 0x38;
pub const STAGE_MP_BASE: u8 = 0x39;
pub const STAGE_TEST_MP2: u8 = 0x3a;
pub const STAGE_MP_AREA52: u8 = 0x3b;
pub const STAGE_MP_WAREHOUSE: u8 = 0x3c;
pub const STAGE_MP_CARPARK: u8 = 0x3d;
pub const STAGE_TEST_MP6: u8 = 0x3e;
pub const STAGE_TEST_MP7: u8 = 0x3f;
pub const STAGE_TEST_MP8: u8 = 0x40;
pub const STAGE_MP_RUINS: u8 = 0x41;
pub const STAGE_MP_SEWERS: u8 = 0x42;
pub const STAGE_MP_FELICITY: u8 = 0x43;
pub const STAGE_MP_FORTRESS: u8 = 0x44;
pub const STAGE_MP_VILLA: u8 = 0x45;
pub const STAGE_TEST_MP14: u8 = 0x46;
pub const STAGE_MP_GRID: u8 = 0x47;
pub const STAGE_TEST_MP16: u8 = 0x48;
pub const STAGE_TEST_MP17: u8 = 0x49;
pub const STAGE_TEST_MP18: u8 = 0x4a;
pub const STAGE_TEST_MP19: u8 = 0x4b;
pub const STAGE_TEST_MP20: u8 = 0x4c;
pub const STAGE_TEST_UFF: u8 = 0x4d;
pub const STAGE_TEST_OLD: u8 = 0x4e;
pub const STAGE_DUEL: u8 = 0x4f;
pub const STAGE_TEST_LAM: u8 = 0x50;
pub const STAGE_TITLE: u8 = 0x5a;
pub const STAGE_BOOTPAKMENU: u8 = 0x5b;
pub const STAGE_CREDITS: u8 = 0x5c;
pub const STAGE_4MBMENU: u8 = 0x5d;

// `g_HeadsAndBodies` rows that are bodies (`constants.h`).
pub const BODY_DJBOND: i32 = 0x0;
pub const BODY_CONNERY: i32 = 0x1;
pub const BODY_DALTON: i32 = 0x2;
pub const BODY_MOORE: i32 = 0x3;
pub const BODY_DARK_COMBAT: i32 = 0x56;
pub const BODY_ELVIS1: i32 = 0x57;
pub const BODY_AREA51GUARD: i32 = 0x58;
pub const BODY_OVERALL: i32 = 0x59;
pub const BODY_CARRINGTON: i32 = 0x5a;
pub const BODY_MRBLONDE: i32 = 0x5b;
pub const BODY_SKEDAR: i32 = 0x5c;
pub const BODY_TRENT: i32 = 0x5d;
pub const BODY_DDSHOCK: i32 = 0x5e;
pub const BODY_LABTECH: i32 = 0x5f;
pub const BODY_STRIPES: i32 = 0x60;
pub const BODY_DARK_FROCK: i32 = 0x61;
pub const BODY_DARK_TRENCH: i32 = 0x62;
pub const BODY_OFFICEWORKER: i32 = 0x63;
pub const BODY_OFFICEWORKER2: i32 = 0x64;
pub const BODY_SECRETARY: i32 = 0x65;
pub const BODY_CASSANDRA: i32 = 0x66;
pub const BODY_THEKING: i32 = 0x67;
pub const BODY_FEM_GUARD: i32 = 0x68;
pub const BODY_DD_LABTECH: i32 = 0x69;
pub const BODY_DD_SECGUARD: i32 = 0x6a;
pub const BODY_DRCAROLL: i32 = 0x6b;
pub const BODY_EYESPY: i32 = 0x6c;
pub const BODY_DARK_RIPPED: i32 = 0x6d;
pub const BODY_DD_GUARD: i32 = 0x6e;
pub const BODY_DD_SHOCK_INF: i32 = 0x6f;
pub const BODY_TESTCHR: i32 = 0x70;
pub const BODY_BIOTECH: i32 = 0x71;
pub const BODY_FBIGUY: i32 = 0x72;
pub const BODY_CIAGUY: i32 = 0x73;
pub const BODY_A51TROOPER: i32 = 0x74;
pub const BODY_A51AIRMAN: i32 = 0x75;
pub const BODY_CHICROB: i32 = 0x76;
pub const BODY_STEWARD: i32 = 0x77;
pub const BODY_STEWARDESS: i32 = 0x78;
pub const BODY_PRESIDENT: i32 = 0x79;
pub const BODY_STEWARDESS_COAT: i32 = 0x7a;
pub const BODY_MINISKEDAR: i32 = 0x7b;
pub const BODY_NSA_LACKEY: i32 = 0x7c;
pub const BODY_PRES_SECURITY: i32 = 0x7d;
pub const BODY_NEGOTIATOR: i32 = 0x7e;
pub const BODY_G5_GUARD: i32 = 0x7f;
pub const BODY_PELAGIC_GUARD: i32 = 0x80;
pub const BODY_G5_SWAT_GUARD: i32 = 0x81;
pub const BODY_ALASKAN_GUARD: i32 = 0x82;
pub const BODY_MAIAN_SOLDIER: i32 = 0x83;
pub const BODY_PRESIDENT_CLONE: i32 = 0x84;
pub const BODY_PRESIDENT_CLONE2: i32 = 0x85;
pub const BODY_DARK_AF1: i32 = 0x86;
pub const BODY_DARKWET: i32 = 0x87;
pub const BODY_DARKAQUALUNG: i32 = 0x88;
pub const BODY_DARKSNOW: i32 = 0x89;
pub const BODY_DARKLAB: i32 = 0x8a;
pub const BODY_FEMLABTECH: i32 = 0x8b;
pub const BODY_DDSNIPER: i32 = 0x8c;
pub const BODY_PILOTAF1: i32 = 0x8d;
pub const BODY_CILABTECH: i32 = 0x8e;
pub const BODY_CIFEMTECH: i32 = 0x8f;
pub const BODY_CARREVENINGSUIT: i32 = 0x90;
pub const BODY_JONATHAN: i32 = 0x91;
pub const BODY_CISOLDIER: i32 = 0x92;
pub const BODY_SKEDARKING: i32 = 0x93;
pub const BODY_ELVISWAISTCOAT: i32 = 0x94;
pub const BODY_DARK_LEATHER: i32 = 0x95;
pub const BODY_DARK_NEGOTIATOR: i32 = 0x96;

// `g_HeadsAndBodies` rows that are heads (`constants.h`).
pub const HEAD_RANDOM: i32 = -0x1;
pub const HEAD_DARK_COMBAT: i32 = 0x4;
pub const HEAD_ELVIS: i32 = 0x5;
pub const HEAD_ROSS: i32 = 0x6;
pub const HEAD_CARRINGTON: i32 = 0x7;
pub const HEAD_MRBLONDE: i32 = 0x8;
pub const HEAD_TRENT: i32 = 0x9;
pub const HEAD_DDSHOCK: i32 = 0xa;
pub const HEAD_GRAHAM: i32 = 0xb;
pub const HEAD_DARK_FROCK: i32 = 0xc;
pub const HEAD_SECRETARY: i32 = 0xd;
pub const HEAD_CASSANDRA: i32 = 0xe;
pub const HEAD_THEKING: i32 = 0xf;
pub const HEAD_FEM_GUARD: i32 = 0x10;
pub const HEAD_JON: i32 = 0x11;
pub const HEAD_MARK2: i32 = 0x12;
pub const HEAD_CHRIST: i32 = 0x13;
pub const HEAD_RUSS: i32 = 0x14;
pub const HEAD_GREY: i32 = 0x15;
pub const HEAD_DARLING: i32 = 0x16;
pub const HEAD_ROBERT: i32 = 0x17;
pub const HEAD_BEAU1: i32 = 0x18;
pub const HEAD_FEM_GUARD2: i32 = 0x19;
pub const HEAD_BRIAN: i32 = 0x1a;
pub const HEAD_JAMIE: i32 = 0x1b;
pub const HEAD_DUNCAN2: i32 = 0x1c;
pub const HEAD_BIOTECH: i32 = 0x1d;
pub const HEAD_NEIL2: i32 = 0x1e;
pub const HEAD_EDMCG: i32 = 0x1f;
pub const HEAD_ANKA: i32 = 0x20;
pub const HEAD_LESLIE_S: i32 = 0x21;
pub const HEAD_MATT_C: i32 = 0x22;
pub const HEAD_PEER_S: i32 = 0x23;
pub const HEAD_EILEEN_T: i32 = 0x24;
pub const HEAD_ANDY_R: i32 = 0x25;
pub const HEAD_BEN_R: i32 = 0x26;
pub const HEAD_STEVE_K: i32 = 0x27;
pub const HEAD_JONATHAN: i32 = 0x28;
pub const HEAD_MAIAN_S: i32 = 0x29;
pub const HEAD_SHAUN: i32 = 0x2a;
pub const HEAD_BEAU2: i32 = 0x2b;
pub const HEAD_EILEEN_H: i32 = 0x2c;
pub const HEAD_SCOTT_H: i32 = 0x2d;
pub const HEAD_SANCHEZ: i32 = 0x2e;
pub const HEAD_DARKAQUA: i32 = 0x2f;
pub const HEAD_DDSNIPER: i32 = 0x30;
pub const HEAD_BEAU3: i32 = 0x31;
pub const HEAD_BEAU4: i32 = 0x32;
pub const HEAD_BEAU5: i32 = 0x33;
pub const HEAD_BEAU6: i32 = 0x34;
pub const HEAD_GRIFFEY: i32 = 0x35;
pub const HEAD_MOTO: i32 = 0x36;
pub const HEAD_KEITH: i32 = 0x37;
pub const HEAD_WINNER: i32 = 0x38;
pub const HEAD_A51FACEPLATE: i32 = 0x39;
pub const HEAD_ELVIS_GOGS: i32 = 0x3a;
pub const HEAD_STEVEM: i32 = 0x3b;
pub const HEAD_DARK_SNOW: i32 = 0x3c;
pub const HEAD_PRESIDENT: i32 = 0x3d;
pub const HEAD_VD: i32 = 0x3e;
pub const HEAD_KEN: i32 = 0x3f;
pub const HEAD_JOEL: i32 = 0x40;
pub const HEAD_TIM: i32 = 0x41;
pub const HEAD_GRANT: i32 = 0x42;
pub const HEAD_PENNY: i32 = 0x43;
pub const HEAD_ROBIN: i32 = 0x44;
pub const HEAD_ALEX: i32 = 0x45;
pub const HEAD_JULIANNE: i32 = 0x46;
pub const HEAD_LAURA: i32 = 0x47;
pub const HEAD_DAVEC: i32 = 0x48;
pub const HEAD_COOK: i32 = 0x49;
pub const HEAD_PRYCE: i32 = 0x4a;
pub const HEAD_SILKE: i32 = 0x4b;
pub const HEAD_SMITH: i32 = 0x4c;
pub const HEAD_GARETH: i32 = 0x4d;
pub const HEAD_MURCHIE: i32 = 0x4e;
pub const HEAD_WONG: i32 = 0x4f;
pub const HEAD_CARTER: i32 = 0x50;
pub const HEAD_TINTIN: i32 = 0x51;
pub const HEAD_MUNTON: i32 = 0x52;
pub const HEAD_STAMPER: i32 = 0x53;
pub const HEAD_JONES: i32 = 0x54;
pub const HEAD_PHELPS: i32 = 0x55;

// `g_MpBodies` indexes.
pub const MPBODY_DARK_COMBAT: u8 = 0x0;
pub const MPBODY_DARK_TRENCH: u8 = 0x1;
pub const MPBODY_DARK_FROCK: u8 = 0x2;
pub const MPBODY_DARK_RIPPED: u8 = 0x3;
pub const MPBODY_DARK_AF1: u8 = 0x4;
pub const MPBODY_DARK_LEATHER: u8 = 0x5;
pub const MPBODY_DARK_NEGOTIATOR: u8 = 0x6;
pub const MPBODY_DARKWET: u8 = 0x7;
pub const MPBODY_DARKAQUALUNG: u8 = 0x8;
pub const MPBODY_DARKSNOW: u8 = 0x9;
pub const MPBODY_DARKLAB: u8 = 0xa;
pub const MPBODY_THEKING: u8 = 0xb;
pub const MPBODY_ELVIS1: u8 = 0xc;
pub const MPBODY_ELVISWAISTCOAT: u8 = 0xd;
pub const MPBODY_CARRINGTON: u8 = 0xe;
pub const MPBODY_CARREVENINGSUIT: u8 = 0xf;
pub const MPBODY_MRBLONDE: u8 = 0x10;
pub const MPBODY_CASSANDRA: u8 = 0x11;
pub const MPBODY_TRENT: u8 = 0x12;
pub const MPBODY_JONATHAN: u8 = 0x13;
pub const MPBODY_CILABTECH: u8 = 0x14;
pub const MPBODY_CIFEMTECH: u8 = 0x15;
pub const MPBODY_CISOLDIER: u8 = 0x16;
pub const MPBODY_DDSHOCK: u8 = 0x17;
pub const MPBODY_FEM_GUARD: u8 = 0x18;
pub const MPBODY_DD_SECGUARD: u8 = 0x19;
pub const MPBODY_DD_GUARD: u8 = 0x1a;
pub const MPBODY_DD_SHOCK_INF: u8 = 0x1b;
pub const MPBODY_SECRETARY: u8 = 0x1c;
pub const MPBODY_OFFICEWORKER: u8 = 0x1d;
pub const MPBODY_OFFICEWORKER2: u8 = 0x1e;
pub const MPBODY_NEGOTIATOR: u8 = 0x1f;
pub const MPBODY_DDSNIPER: u8 = 0x20;
pub const MPBODY_G5_GUARD: u8 = 0x21;
pub const MPBODY_G5_SWAT_GUARD: u8 = 0x22;
pub const MPBODY_CIAGUY: u8 = 0x23;
pub const MPBODY_FBIGUY: u8 = 0x24;
pub const MPBODY_AREA51GUARD: u8 = 0x25;
pub const MPBODY_A51TROOPER: u8 = 0x26;
pub const MPBODY_A51AIRMAN: u8 = 0x27;
pub const MPBODY_OVERALL: u8 = 0x28;
pub const MPBODY_STRIPES: u8 = 0x29;
pub const MPBODY_LABTECH: u8 = 0x2a;
pub const MPBODY_FEMLABTECH: u8 = 0x2b;
pub const MPBODY_DD_LABTECH: u8 = 0x2c;
pub const MPBODY_BIOTECH: u8 = 0x2d;
pub const MPBODY_ALASKAN_GUARD: u8 = 0x2e;
pub const MPBODY_PILOTAF1: u8 = 0x2f;
pub const MPBODY_STEWARD: u8 = 0x30;
pub const MPBODY_STEWARDESS: u8 = 0x31;
pub const MPBODY_STEWARDESS_COAT: u8 = 0x32;
pub const MPBODY_PRESIDENT: u8 = 0x33;
pub const MPBODY_NSA_LACKEY: u8 = 0x34;
pub const MPBODY_PRES_SECURITY: u8 = 0x35;
pub const MPBODY_PRESIDENT_CLONE2: u8 = 0x36;
pub const MPBODY_PELAGIC_GUARD: u8 = 0x37;
pub const MPBODY_MAIAN_SOLDIER: u8 = 0x38;
pub const MPBODY_CONNERY: u8 = 0x39;
pub const MPBODY_MOORE: u8 = 0x3a;
pub const MPBODY_DALTON: u8 = 0x3b;
pub const MPBODY_DJBOND: u8 = 0x3c;

// `g_MpHeads` indexes.
pub const MPHEAD_DARK_COMBAT: u8 = 0x0;
pub const MPHEAD_DARK_FROCK: u8 = 0x1;
pub const MPHEAD_DARKAQUA: u8 = 0x2;
pub const MPHEAD_DARK_SNOW: u8 = 0x3;
pub const MPHEAD_ELVIS: u8 = 0x4;
pub const MPHEAD_ELVIS_GOGS: u8 = 0x5;
pub const MPHEAD_CARRINGTON: u8 = 0x6;
pub const MPHEAD_MRBLONDE: u8 = 0x7;
pub const MPHEAD_CASSANDRA: u8 = 0x8;
pub const MPHEAD_TRENT: u8 = 0x9;
pub const MPHEAD_JONATHAN: u8 = 0xa;
pub const MPHEAD_VD: u8 = 0xb;
pub const MPHEAD_PRESIDENT: u8 = 0xc;
pub const MPHEAD_DDSHOCK: u8 = 0xd;
pub const MPHEAD_BIOTECH: u8 = 0xe;
pub const MPHEAD_DDSNIPER: u8 = 0xf;
pub const MPHEAD_A51FACEPLATE: u8 = 0x10;
pub const MPHEAD_SECRETARY: u8 = 0x11;
pub const MPHEAD_FEM_GUARD: u8 = 0x12;
pub const MPHEAD_FEM_GUARD2: u8 = 0x13;
pub const MPHEAD_MAIAN_S: u8 = 0x14;
pub const MPHEAD_JON: u8 = 0x15;
pub const MPHEAD_BEAU1: u8 = 0x16;
pub const MPHEAD_ROSS: u8 = 0x17;
pub const MPHEAD_MARK2: u8 = 0x18;
pub const MPHEAD_CHRIST: u8 = 0x19;
pub const MPHEAD_RUSS: u8 = 0x1a;
pub const MPHEAD_DARLING: u8 = 0x1b;
pub const MPHEAD_BRIAN: u8 = 0x1c;
pub const MPHEAD_JAMIE: u8 = 0x1d;
pub const MPHEAD_DUNCAN2: u8 = 0x1e;
pub const MPHEAD_KEITH: u8 = 0x1f;
pub const MPHEAD_STEVEM: u8 = 0x20;
pub const MPHEAD_GRANT: u8 = 0x21;
pub const MPHEAD_PENNY: u8 = 0x22;
pub const MPHEAD_DAVEC: u8 = 0x23;
pub const MPHEAD_JONES: u8 = 0x24;
pub const MPHEAD_GRAHAM: u8 = 0x25;
pub const MPHEAD_ROBERT: u8 = 0x26;
pub const MPHEAD_NEIL2: u8 = 0x27;
pub const MPHEAD_SHAUN: u8 = 0x28;
pub const MPHEAD_ROBIN: u8 = 0x29;
pub const MPHEAD_COOK: u8 = 0x2a;
pub const MPHEAD_PRYCE: u8 = 0x2b;
pub const MPHEAD_SILKE: u8 = 0x2c;
pub const MPHEAD_SMITH: u8 = 0x2d;
pub const MPHEAD_GARETH: u8 = 0x2e;
pub const MPHEAD_MURCHIE: u8 = 0x2f;
pub const MPHEAD_WONG: u8 = 0x30;
pub const MPHEAD_CARTER: u8 = 0x31;
pub const MPHEAD_TINTIN: u8 = 0x32;
pub const MPHEAD_MUNTON: u8 = 0x33;
pub const MPHEAD_STAMPER: u8 = 0x34;
pub const MPHEAD_PHELPS: u8 = 0x35;
pub const MPHEAD_ALEX: u8 = 0x36;
pub const MPHEAD_JULIANNE: u8 = 0x37;
pub const MPHEAD_LAURA: u8 = 0x38;
pub const MPHEAD_EDMCG: u8 = 0x39;
pub const MPHEAD_ANKA: u8 = 0x3a;
pub const MPHEAD_LESLIE_S: u8 = 0x3b;
pub const MPHEAD_MATT_C: u8 = 0x3c;
pub const MPHEAD_PEER_S: u8 = 0x3d;
pub const MPHEAD_EILEEN_T: u8 = 0x3e;
pub const MPHEAD_ANDY_R: u8 = 0x3f;
pub const MPHEAD_BEN_R: u8 = 0x40;
pub const MPHEAD_STEVE_K: u8 = 0x41;
pub const MPHEAD_SANCHEZ: u8 = 0x42;
pub const MPHEAD_TIM: u8 = 0x43;
pub const MPHEAD_KEN: u8 = 0x44;
pub const MPHEAD_EILEEN_H: u8 = 0x45;
pub const MPHEAD_SCOTT_H: u8 = 0x46;
pub const MPHEAD_JOEL: u8 = 0x47;
pub const MPHEAD_GRIFFEY: u8 = 0x48;
pub const MPHEAD_MOTO: u8 = 0x49;
pub const MPHEAD_WINNER: u8 = 0x4a;

// Scenarios.
pub const MPSCENARIO_COMBAT: u8 = 0;
pub const MPSCENARIO_HOLDTHEBRIEFCASE: u8 = 1;
pub const MPSCENARIO_HACKERCENTRAL: u8 = 2;
pub const MPSCENARIO_POPACAP: u8 = 3;
pub const MPSCENARIO_KINGOFTHEHILL: u8 = 4;
pub const MPSCENARIO_CAPTURETHECASE: u8 = 5;

// `g_MpSetup.options` flags.
pub const MPOPTION_ONEHITKILLS: u32 = 0x1;
pub const MPOPTION_TEAMSENABLED: u32 = 0x2;
pub const MPOPTION_NORADAR: u32 = 0x4;
pub const MPOPTION_NOAUTOAIM: u32 = 0x8;
pub const MPOPTION_NOPLAYERHIGHLIGHT: u32 = 0x10;
pub const MPOPTION_NOPICKUPHIGHLIGHT: u32 = 0x20;
pub const MPOPTION_SLOWMOTION_ON: u32 = 0x40;
pub const MPOPTION_SLOWMOTION_SMART: u32 = 0x80;
pub const MPOPTION_FASTMOVEMENT: u32 = 0x100;
pub const MPOPTION_DISPLAYTEAM: u32 = 0x200;
pub const MPOPTION_KILLSSCORE: u32 = 0x400;
pub const MPOPTION_HTB_HIGHLIGHTBRIEFCASE: u32 = 0x800;
pub const MPOPTION_HTB_SHOWONRADAR: u32 = 0x1000;
pub const MPOPTION_CTC_SHOWONRADAR: u32 = 0x2000;
pub const MPOPTION_KOH_HILLONRADAR: u32 = 0x4000;
pub const MPOPTION_KOH_MOBILEHILL: u32 = 0x8000;
pub const MPOPTION_00010000: u32 = 0x10000;
pub const MPOPTION_HTM_HIGHLIGHTTERMINAL: u32 = 0x20000;
pub const MPOPTION_HTM_SHOWONRADAR: u32 = 0x40000;
pub const MPOPTION_PAC_HIGHLIGHTTARGET: u32 = 0x80000;
pub const MPOPTION_PAC_SHOWONRADAR: u32 = 0x100000;

// Unlockable features (`g_MpFeaturesUnlocked`).
pub const MPFEATURE_WEAPON_FARSIGHT: u8 = 0x1;
pub const MPFEATURE_WEAPON_TRANQUILIZER: u8 = 0x2;
pub const MPFEATURE_WEAPON_SUPERDRAGON: u8 = 0x3;
pub const MPFEATURE_WEAPON_SLAYER: u8 = 0x4;
pub const MPFEATURE_WEAPON_FALCON2SILENCED: u8 = 0x5;
pub const MPFEATURE_WEAPON_FALCON2SCOPE: u8 = 0x6;
pub const MPFEATURE_WEAPON_MAULER: u8 = 0x7;
pub const MPFEATURE_WEAPON_PHOENIX: u8 = 0x8;
pub const MPFEATURE_WEAPON_DY357LX: u8 = 0x9;
pub const MPFEATURE_WEAPON_CALLISTO: u8 = 0xa;
pub const MPFEATURE_WEAPON_LAPTOPGUN: u8 = 0xb;
pub const MPFEATURE_WEAPON_K7AVENGER: u8 = 0xc;
pub const MPFEATURE_WEAPON_RCP120: u8 = 0xd;
pub const MPFEATURE_WEAPON_SHOTGUN: u8 = 0xe;
pub const MPFEATURE_WEAPON_REAPER: u8 = 0xf;
pub const MPFEATURE_WEAPON_DEVASTATOR: u8 = 0x10;
pub const MPFEATURE_WEAPON_CROSSBOW: u8 = 0x11;
pub const MPFEATURE_WEAPON_NBOMB: u8 = 0x12;
pub const MPFEATURE_WEAPON_PROXIMITYMINE: u8 = 0x13;
pub const MPFEATURE_WEAPON_REMOTEMINE: u8 = 0x14;
pub const MPFEATURE_WEAPON_XRAYSCANNER: u8 = 0x15;
pub const MPFEATURE_WEAPON_SHIELD: u8 = 0x16;
pub const MPFEATURE_WEAPON_CLOAKINGDEVICE: u8 = 0x17;
pub const MPFEATURE_WEAPON_COMBATBOOST: u8 = 0x18;
pub const MPFEATURE_BOTDIFF_HARD: u8 = 0x19;
pub const MPFEATURE_BOTDIFF_PERFECT: u8 = 0x1a;
pub const MPFEATURE_1B: u8 = 0x1b;
pub const MPFEATURE_BOTDIFF_DARK: u8 = 0x1c;
pub const MPFEATURE_SLOWMOTION: u8 = 0x1d;
pub const MPFEATURE_ONEHITKILLS: u8 = 0x1e;
pub const MPFEATURE_SCENARIO_KOH: u8 = 0x1f;
pub const MPFEATURE_SCENARIO_HTB: u8 = 0x20;
pub const MPFEATURE_SCENARIO_CTC: u8 = 0x21;
pub const MPFEATURE_22: u8 = 0x22;
pub const MPFEATURE_STAGE_CARPARK: u8 = 0x23;
pub const MPFEATURE_STAGE_COMPLEX: u8 = 0x24;
pub const MPFEATURE_STAGE_WAREHOUSE: u8 = 0x25;
pub const MPFEATURE_STAGE_RAVINE: u8 = 0x26;
pub const MPFEATURE_STAGE_TEMPLE: u8 = 0x27;
pub const MPFEATURE_STAGE_G5BUILDING: u8 = 0x28;
pub const MPFEATURE_STAGE_GRID: u8 = 0x29;
pub const MPFEATURE_STAGE_FELICITY: u8 = 0x2a;
pub const MPFEATURE_STAGE_VILLA: u8 = 0x2b;
pub const MPFEATURE_STAGE_SEWERS: u8 = 0x2c;
pub const MPFEATURE_STAGE_RUINS: u8 = 0x2d;
pub const MPFEATURE_STAGE_BASE: u8 = 0x2e;
pub const MPFEATURE_2F: u8 = 0x2f;
pub const MPFEATURE_STAGE_FORTRESS: u8 = 0x30;
pub const MPFEATURE_31: u8 = 0x31;
pub const MPFEATURE_CHR_FEMGUARD: u8 = 0x32;
pub const MPFEATURE_CHR_OFFICEWORKER: u8 = 0x33;
pub const MPFEATURE_CHR_VILLACHRS: u8 = 0x34;
pub const MPFEATURE_CHR_TRENT: u8 = 0x35;
pub const MPFEATURE_CHR_NSALACKEY: u8 = 0x36;
pub const MPFEATURE_CHR_G5: u8 = 0x37;
pub const MPFEATURE_CHR_MRBLONDE: u8 = 0x38;
pub const MPFEATURE_CHR_CIAFBI: u8 = 0x39;
pub const MPFEATURE_CHR_INFILTRATION: u8 = 0x3a;
pub const MPFEATURE_CHR_LABTECH: u8 = 0x3b;
pub const MPFEATURE_CHR_BIOTECH: u8 = 0x3c;
pub const MPFEATURE_CHR_ELVIS: u8 = 0x3d;
pub const MPFEATURE_CHR_ALASKANGUARD: u8 = 0x3e;
pub const MPFEATURE_CHR_AF1: u8 = 0x3f;
pub const MPFEATURE_8BOTS: u8 = 0x40;
pub const MPFEATURE_CHR_CI: u8 = 0x41;
pub const MPFEATURE_CHR_PRESCLONE: u8 = 0x42;
pub const MPFEATURE_CHR_PRESSECURITY: u8 = 0x43;
pub const MPFEATURE_CHR_STRIPES: u8 = 0x44;
pub const MPFEATURE_CHR_PELAGIC: u8 = 0x45;
pub const MPFEATURE_CHR_JOTRENCH: u8 = 0x46;
pub const MPFEATURE_CHR_JOSNOW: u8 = 0x47;
pub const MPFEATURE_48: u8 = 0x48;
pub const MPFEATURE_49: u8 = 0x49;
pub const MPFEATURE_CHR_DARKSNOW: u8 = 0x4a;
pub const MPFEATURE_4B: u8 = 0x4b;
pub const MPFEATURE_CHR_JONATHAN: u8 = 0x4c;
pub const MPFEATURE_SCENARIO_PAC: u8 = 0x4d;
pub const MPFEATURE_SCENARIO_HTM: u8 = 0x4e;
pub const MPFEATURE_WEAPON_LASER: u8 = 0x4f;

// Simulant difficulties.
pub const BOTDIFF_MEAT: u8 = 0;
pub const BOTDIFF_EASY: u8 = 1;
pub const BOTDIFF_NORMAL: u8 = 2;
pub const BOTDIFF_HARD: u8 = 3;
pub const BOTDIFF_PERFECT: u8 = 4;
pub const BOTDIFF_DARK: u8 = 5;
pub const BOTDIFF_DISABLED: u8 = 6;

// Simulant personalities.
pub const BOTTYPE_GENERAL: u8 = 0;
pub const BOTTYPE_PEACE: u8 = 1;
pub const BOTTYPE_SHIELD: u8 = 2;
pub const BOTTYPE_ROCKET: u8 = 3;
pub const BOTTYPE_KAZE: u8 = 4;
pub const BOTTYPE_FIST: u8 = 5;
pub const BOTTYPE_PREY: u8 = 6;
pub const BOTTYPE_COWARD: u8 = 7;
pub const BOTTYPE_JUDGE: u8 = 8;
pub const BOTTYPE_FEUD: u8 = 9;
pub const BOTTYPE_SPEED: u8 = 10;
pub const BOTTYPE_TURTLE: u8 = 11;
pub const BOTTYPE_VENGE: u8 = 12;

// Body parts a shot can hit (`chr_damage`'s multipliers).
pub const HITPART_LFOOT: i32 = 1;
pub const HITPART_LSHIN: i32 = 2;
pub const HITPART_LTHIGH: i32 = 3;
pub const HITPART_RFOOT: i32 = 4;
pub const HITPART_RSHIN: i32 = 5;
pub const HITPART_RTHIGH: i32 = 6;
pub const HITPART_PELVIS: i32 = 7;
pub const HITPART_HEAD: i32 = 8;
pub const HITPART_LHAND: i32 = 9;
pub const HITPART_LFOREARM: i32 = 10;
pub const HITPART_LBICEP: i32 = 11;
pub const HITPART_RHAND: i32 = 12;
pub const HITPART_RFOREARM: i32 = 13;
pub const HITPART_RBICEP: i32 = 14;
pub const HITPART_TORSO: i32 = 15;
pub const HITPART_TAIL: i32 = 16;
pub const HITPART_GUN: i32 = 100;
pub const HITPART_HAT: i32 = 110;
pub const HITPART_GENERAL: i32 = 200;
pub const HITPART_GENERALHALF: i32 = 201;

/// Each `g_Stages` row's stage and code (its BG file, `stagetable.c`): the
/// name of `assets/stages/<code>/`.
pub const STAGE_CODES: &[(u8, &str)] = &[
    (STAGE_MAIANSOS, "lue"),
    (STAGE_TEST_SILO, "oat"),
    (STAGE_WAR, "sho"),
    (STAGE_MP_RAVINE, "arec"),
    (STAGE_TEST_ARCH, "arch"),
    (STAGE_ESCAPE, "lue"),
    (STAGE_TEST_DEST, "dest"),
    (STAGE_RETAKING, "dish"),
    (STAGE_CRASHSITE, "azt"),
    (STAGE_CHICAGO, "pete"),
    (STAGE_G5BUILDING, "depo"),
    (STAGE_MP_COMPLEX, "ref"),
    (STAGE_MP_G5BUILDING, "cryp"),
    (STAGE_PELAGIC, "dam"),
    (STAGE_EXTRACTION, "ame"),
    (STAGE_TEST_RUN, "run"),
    (STAGE_24, "sevx"),
    (STAGE_MP_TEMPLE, "jun"),
    (STAGE_CITRAINING, "dish"),
    (STAGE_AIRBASE, "cave"),
    (STAGE_28, "cat"),
    (STAGE_MP_PIPES, "crad"),
    (STAGE_SKEDARRUINS, "sho"),
    (STAGE_2B, "sevx"),
    (STAGE_VILLA, "eld"),
    (STAGE_DEFENSE, "dish"),
    (STAGE_TEST_ASH, "ash"),
    (STAGE_INFILTRATION, "lue"),
    (STAGE_DEFECTION, "ame"),
    (STAGE_AIRFORCEONE, "rit"),
    (STAGE_MP_SKEDAR, "oat"),
    (STAGE_INVESTIGATION, "ear"),
    (STAGE_ATTACKSHIP, "lee"),
    (STAGE_RESCUE, "lue"),
    (STAGE_TEST_LEN, "len"),
    (STAGE_MBR, "ame"),
    (STAGE_DEEPSEA, "pam"),
    (STAGE_TEST_UFF, "uff"),
    (STAGE_TEST_OLD, "old"),
    (STAGE_DUEL, "dish"),
    (STAGE_TEST_LAM, "lam"),
    (STAGE_MP_BASE, "mp1"),
    (STAGE_TEST_MP2, "mp2"),
    (STAGE_MP_AREA52, "mp3"),
    (STAGE_MP_WAREHOUSE, "mp4"),
    (STAGE_MP_CARPARK, "mp5"),
    (STAGE_TEST_MP6, "mp6"),
    (STAGE_TEST_MP7, "mp7"),
    (STAGE_TEST_MP8, "mp8"),
    (STAGE_MP_RUINS, "mp9"),
    (STAGE_MP_SEWERS, "mp10"),
    (STAGE_MP_FELICITY, "mp11"),
    (STAGE_MP_FORTRESS, "mp12"),
    (STAGE_MP_VILLA, "mp13"),
    (STAGE_TEST_MP14, "mp14"),
    (STAGE_MP_GRID, "mp15"),
    (STAGE_TEST_MP16, "mp16"),
    (STAGE_TEST_MP17, "mp17"),
    (STAGE_TEST_MP18, "mp18"),
    (STAGE_TEST_MP19, "mp19"),
    (STAGE_TEST_MP20, "mp20"),
];

/// A stage's code (`STAGE_MP_COMPLEX` -> `"ref"`).
pub fn stage_code(stage: u8) -> Option<&'static str> {
    STAGE_CODES.iter().find(|(s, _)| *s == stage).map(|(_, c)| *c)
}
