#!/usr/bin/env python3
"""Generate `crates/pd_core/src/ids.rs`: PD's enumerations under PD's names.

From `include/constants.h` (NTSC final): `WEAPON_*` (enum weaponnum and the
defines beside it), `STAGE_*`, `BODY_*`, `HEAD_*`, `MPBODY_*`, `MPHEAD_*`,
`MPSCENARIO_*`, `MPOPTION_*`, `MPFEATURE_*`, `BOTDIFF_*`, `BOTTYPE_*`,
`HITPART_*`, `GEOFLAG_*`, `PADFLAG_*`, `FLOORTYPE_*`, `CROUCHPOS_*`; and from `game/stagetable.c` each stage's code (its BG file,
`FILE_BG_REF_SEG` -> "ref"), which names `assets/stages/<code>/`.

Sound ids (`sfx.h`) are keyed in `assets/sfx/manifest.json` and file numbers
(`files.h`) in `assets/models/index.json`, so neither is generated here.

Usage:
    python tools/pd-assets/pd_ids.py        # build_assets.py runs it too
"""

from __future__ import annotations

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import pd_weapons  # noqa: E402
from pd_paths import REPO, src  # noqa: E402

OUT = os.path.join(REPO, "crates", "pd_core", "src", "ids.rs")

#: (prefix, Rust type, hex?, doc)
GROUPS = [
    ("WEAPON_", "u8", False, "`enum weaponnum` (`constants.h:4561`) and the `WEAPON_*` defines."),
    ("STAGE_", "u8", True, "Stage numbers (`constants.h`)."),
    ("BODY_", "i32", True, "`g_HeadsAndBodies` rows that are bodies (`constants.h`)."),
    ("HEAD_", "i32", True, "`g_HeadsAndBodies` rows that are heads (`constants.h`)."),
    ("MPBODY_", "u8", True, "`g_MpBodies` indexes."),
    ("MPHEAD_", "u8", True, "`g_MpHeads` indexes."),
    ("MPSCENARIO_", "u8", False, "Scenarios."),
    ("MPOPTION_", "u32", True, "`g_MpSetup.options` flags."),
    ("MPFEATURE_", "u8", True, "Unlockable features (`g_MpFeaturesUnlocked`)."),
    ("BOTDIFF_", "u8", False, "Simulant difficulties."),
    ("BOTTYPE_", "u8", False, "Simulant personalities."),
    ("HITPART_", "i32", False, "Body parts a shot can hit (`chr_damage`'s multipliers)."),
    ("GEOFLAG_", "u32", True, "Collision tile flags (`constants.h:1189`)."),
    ("PADFLAG_", "u32", True, "Pad flags (`constants.h:3321`)."),
    ("FLOORTYPE_", "u8", False, "Floor materials, for footsteps (`constants.h:961`)."),
    ("CROUCHPOS_", "i32", False, "The player's crouch levels (`currentplayer->crouchpos`)."),
]


def stage_codes(values: dict[str, int]) -> list[tuple[str, int, str]]:
    """(STAGE_ name, number, code) for every `g_Stages` row (`stagetable.c`)."""
    text = open(src("game", "stagetable.c"), encoding="utf-8").read()
    out = []
    for m in re.finditer(r"/\*0x[0-9a-f]+\*/\s*(STAGE_\w+)\s*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*,\s*FILE_BG_(\w+?)_SEG", text):
        name, code = m.group(1), m.group(2).lower()
        out.append((name, values[name], code))
    return out


def main() -> int:
    pd_weapons.require_decomp()
    header = src("include", "constants.h")
    values = pd_weapons.scrape_defines(header, tuple(p for p, *_ in GROUPS))
    values.update(pd_weapons.scrape_enums(header, ("weaponnum",)))
    lines = [
        "//! GENERATED by tools/pd-assets/pd_ids.py from reference/pd-decomp (NTSC final). Do not edit:",
        "//! change the generator and rerun it.",
        "//!",
        "//! PD's enumerations under PD's names, so a value can be looked up in the decomp",
        "//! directly. Sound ids are keyed in `assets/sfx/manifest.json` and FILE_* numbers in",
        "//! `assets/models/index.json`.",
        "#![allow(dead_code)]",
        "",
    ]
    total = 0
    for prefix, ty, hexa, doc in GROUPS:
        names = sorted((n for n in values if n.startswith(prefix)), key=lambda n: (values[n], n))
        lines.append(f"// {doc}")
        for n in names:
            v = values[n]
            if ty.startswith("u") and v < 0:
                continue
            lit = (f"{v:#x}" if v >= 0 else f"-{-v:#x}") if hexa else str(v)
            lines.append(f"pub const {n}: {ty} = {lit};")
            total += 1
        lines.append("")
    stages = stage_codes(values)
    lines.append("/// Each `g_Stages` row's stage and code (its BG file, `stagetable.c`): the")
    lines.append("/// name of `assets/stages/<code>/`.")
    lines.append("pub const STAGE_CODES: &[(u8, &str)] = &[")
    for name, v, code in stages:
        lines.append(f"    ({name}, \"{code}\"),")
    lines.append("];")
    lines.append("")
    lines.append("/// A stage's code (`STAGE_MP_COMPLEX` -> `\"ref\"`).")
    lines.append("pub fn stage_code(stage: u8) -> Option<&'static str> {")
    lines.append("    STAGE_CODES.iter().find(|(s, _)| *s == stage).map(|(_, c)| *c)")
    lines.append("}")
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"pd_ids: {total} constants, {len(stages)} stage codes -> {os.path.relpath(OUT, REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
